### ISSUE TITLE
Error deploying 1.2.0

### ISSUE THREAD

**Issue by negberts** [microsoft/service-fabric-healer#144]
Trying to deploy version 1.2.0 to our cluster. Both the self-contained and framework dependent throw the below error.

Happens during upgrade as well as clean install with previous version removed from the cluster.

Cluster is at version 9.1.1436.9590

{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.","details":[{"code":"ClusterChildResourceOperationFailed","message":"Resource operation failed. Operation: CreateOrUpdate. Error details: {\r\n  \"Details\": {\r\n    \"ClassName\": \"System.Fabric.FabricException\",\r\n    \"Message\": \"Parameter 'MonitorLoopSleepSeconds' is not defined in the ApplicationManifest file.\\r\\nFileName: applicationParameters\",\r\n    \"Data\": null,\r\n    \"InnerException\": {\r\n      \"ClassName\": \"System.Runtime.InteropServices.COMException\",\r\n      \"Message\": \"Exception from HRESULT: 0x80071BE6\",\r\n      \"Data\": null,\r\n      \"InnerException\": null,\r\n      \"HelpURL\": null,\r\n      \"StackTraceString\": \"   at System.Fabric.Interop.NativeClient.IFabricApplicationManagementClient10.EndCreateApplication(IFabricAsyncOperationContext context)\\r\\n   at System.Fabric.Interop.Utility.<>c__DisplayClass22_0.<WrapNativeAsyncInvoke>b__0(IFabricAsyncOperationContext context)\\r\\n   at System.Fabric.Interop.AsyncCallOutAdapter2`1.Finish(IFabricAsyncOperationContext context, Boolean expectedCompletedSynchronously)\",\r\n      \"RemoteStackTraceString\": null,\r\n      \"RemoteStackIndex\": 0,\r\n      \"ExceptionMethod\": \"8\\nEndCreateApplication\\nSystem.Fabric, Version=9.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35\\nSystem.Fabric.Interop.NativeClient+IFabricApplicationManagementClient10\\nVoid EndCreateApplication(IFabricAsyncOperationContext)\",\r\n      \"HResult\": -2147017754,\r\n      \"Source\": \"System.Fabric\",\r\n      \"WatsonBuckets\": null\r\n    },\r\n    \"HelpURL\": null,\r\n    \"StackTraceString\": \"   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\r\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\r\\n   at System.Fabric.UpgradeService.ApplicationClient.<CreateAsync>d__8.MoveNext()\\r\\n--- End of stack trace from previous location where exception was thrown ---\\r\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\r\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\r\\n   at System.Fabric.UpgradeService.ApplicationCommandProcessor.<CreateOperationStatusAsync>d__9.MoveNext()\",\r\n    \"RemoteStackTraceString\": null,\r\n    \"RemoteStackIndex\": 0,\r\n    \"ExceptionMethod\": \"8\\nThrow\\nmscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089\\nSystem.Runtime.ExceptionServices.ExceptionDispatchInfo\\nVoid Throw()\",\r\n    \"HResult\": -2147017754,\r\n    \"Source\": \"mscorlib\",\r\n    \"WatsonBuckets\": null\r\n  }\r\n}"}]}

**Comment by GitTorre** [comment]
Hi,

This is a bug in the ARM template. It is now corrected. Sorry about that. 

That parameter name was changed to HealthCheckIntervalInSeconds and this change was not reflected in the ARM template.

**Comment by GitTorre** [comment]
I have verified that ARM deployment is no longer broken due to misnamed application parameter. Please try again.

**Comment by negberts** [comment]
I can confirm that it is fixed :-)
