### ISSUE TITLE
[BUG] Guan files are processed even when the specified repair type is not enabled

### ISSUE THREAD

**Issue by markwragg** [microsoft/service-fabric-healer#150]
**Describe the bug**

I can see the following log entry from FabricHealer:

> TraceCurrentlyExecutingRule failure => Unable to read SystemServiceRules.guan: Index was outside the bounds of the array.

I have the default version of the SystemServiceRules.guan file in FabricHealer, which seems to suggest that in its default form it has a bug (which is perhaps because one of the examples it contains is not intended for actual use). 

However, I currently have `EnableSystemServiceRepair` set to the default value of `false`, so I would have expected the SystemServiceRules.guan file to not even need to be loaded by Fabric Healer.

**Steps To Reproduce**

Deploy FabricHealer with its default setup. The error can be observed in its logs, or in Log Analytics if telemetry is enabled.

**Expected behavior**

The tool should not attempt to load guan files for repair type that it does not have enabled.

**OS:**
 - Name: Windows
 - Version: 2019 Datacenter

**Additional information:**

Fabric Healer version 1.2.1

**Comment by GitTorre** [comment]
This is quite strange. I will look into this. I actually enable this repair for a Linux cluster and have not seen this error re trace rule. That looks like a bug. In terms of processing the rule in the first place if the repair is disabled, that is perplexing and certainly unexpected. Thanks for the report.

**Comment by GitTorre** [comment]
Would you mind verifying the fix in develop branch? I will let you know when I push it.

**Comment by GitTorre** [comment]
@markwragg, can you confirm you are no longer seeing any issues like this in 1.2.2? 

Many thanks,
...Charles

**Comment by markwragg** [comment]
Hi Charles,

This issue looks fixed to me, certainly not seeing that error in the Fabric Healer logs anymore.

I am still struggling to get a disk mitigation to fire though. I've got one setup pretty much per the example, I've filled a C:\ drive to 96% and SFO is showing a warning but it doesn't seem to be executing the mitigation at all to clean up the folders. I'm trying log tracing and if I can't figure it out I'll raise it as a separate issue.

Thanks,
Mark

**Comment by GitTorre** [comment]
Can you share the logic rule you have in place for this warning from FO that is not deleting files?

**Comment by markwragg** [comment]
Here's the full file, in case its otherwise malformed:

```
## Logic rules for Disk repair. Only file management is supported (file deletion). Note that all of these rules expect facts from an external source (FabricObserver or FHProxy).

## Applicable Named Arguments for Mitigate. Corresponding data is supplied by FabricObserver or FHProxy, renamed for brevity by FH.
## | Argument Name             | Definition                                                                                   |
## |---------------------------|----------------------------------------------------------------------------------------------|
## | NodeName                  | Name of the node                                                                             | 
## | NodeType                  | Type of node                                                                                 |  
## | ObserverName              | Name of Observer that generated the event (if data comes from the FabricObserver service)    |
## | ErrorCode                 | Supported Error Code emitted by caller (Disk codes are FO007-FO010, FO042, F0043)            | 
## | MetricName                | Name of the supplied metric                                                                  |   
## | MetricValue               | Corresponding value for supplied metric                                                      | 
## | OS                        | The name of the OS from which the data was collected (Linux or Windows)                      |
## | HealthState               | The HealthState of the target entity: Error or Warning                                       |

## Disk-related Metric Names.
## | Name                      |                                                                                    
## |---------------------------|
## | DiskSpacePercent          |                                         
## | DiskSpaceMB               |    
## | FolderSizeMB              |  

## Currently implemented external predicates for use in Disk repair rules.
## | Name                      | Definition                                                                               
## |---------------------------|---------------------------------------------------------------------------------------------------------------|
## | CheckFolderSize           | Returns true if supplied folder is equal to or larger than specified value.                                   |
## | DeleteFiles               | Deletes files in a specified directory (full path) with optional arguments.                                   |

## First, check if we are inside run interval. If so, then cut (!).
## This is commented out by default. Just uncomment and set the global run interval for disk level repairs to suit your needs.

Mitigate :- CheckInsideRunInterval(02:00:00), !.

## DeleteFiles external predicate takes 1 required positional argument (position 0), which is the full path to the directory to be cleaned, and 4 optional named arguments.
## Optional (named, position 1 to n in argument list, first arg (0) is reserved for folder path) arguments for DeleteFiles: 
##		SortOrder - File sort order, Ascending or Descending. Defaults to Ascending (oldest to newest)).
##		MaxFilesToDelete - The maximum number of files to delete. If not specified (or 0) it will be interpreted to mean delete all files.
##		RecurseSubdirectories - Delete files in child folders of specified directory. Defaults to false if not specified.
##		SearchPattern - Delete only files with file names that match the specified search pattern. Default is "*" (all files).

## The CheckFolderSize external predicate takes a folder path string argument and either a MaxFolderSizeGB or MaxFolderSizeMB argument.
## Required positional arguments for CheckFolderSize external predicate:
##		First argument (0 position in argument list): The full path to the folder to be cleaned.

## Required named arguments (1 through n position in argument list) for CheckFolderSize external predicate:
##		MaxFolderSizezGB: max size of folder in gigabytes.
##      MaxFolderSizezMB: max size of folder in megabytes.

## If CheckFolderSize is true, then the next sub-goal will run, which in the rules below is the DeleteFiles external predicate.

## Added 2023-04-05 | Mark Wragg: Remove files from Service Fabric Observer and Fabric Healer log directories if directories > 1GB

Mitigate(MetricName=?MetricName) :- match(?MetricName, "DiskSpace"), GetRepairHistory(?repairCount, 08:00:00), 
	?repairCount < 4,
	member(config(?X,?Y), [config("C:\cluster_observer_logs", 1), config("C:\fabric_healer_logs", 1), config("C:\fabric_observer_logs", 1)]), 
	CheckFolderSize(?X, MaxFolderSizeGB=?Y),
	DeleteFiles(?X, SortOrder=Ascending, MaxFilesToDelete=10, RecurseSubdirectories=true).

## Added 2023-04-05 | Mark Wragg: Remove ETL files from Service Fabric Log Traces directory if directory > 20GB

Mitigate(MetricName=?MetricName) :- match(?MetricName, "DiskSpace"), GetRepairHistory(?repairCount, 08:00:00),
	?repairCount < 4,
	CheckFolderSize("D:\SvcFab\Log\Traces", MaxFolderSizeGB=20),
	DeleteFiles("D:\SvcFab\Log\Traces", SortOrder=Ascending, MaxFilesToDelete=10, RecurseSubdirectories=true, SearchPattern="*.etl").
```

I wondered if the metricname being "diskspace" was the problem, but then realised because of the `match` function that I assume will match warnings for either MB or Percent. My SFO warns when > 90%. I triggered this by creating 11 x 10GB files inside of C:\fabric_healer_logs which I then expected Fabric Healer to start to remove, but after 2 days its done nothing.

Log tracing didn't real anything either, other than i'm getting no longs at all (I did get some logs when I initially installed FabricHealer at the same time as upgrading to Service Fabric 9.1 where it logged that it wouldn't do repairs while an Upgrade was occurring, so i'm confident it was writing to Log Analytics fine).

In my AppManifest.xml I have disk repair enabled by default:

```
<Parameter Name="EnableDiskRepair" DefaultValue="true" />
```

**Comment by GitTorre** [comment]
I can't reproduce this problem. 
FO generates a Disk Warning (Percent in use..).
FH enabled for Disk Repair

Using the rules you provided above, with target folder (C:\cluster_observer_logs) size exceeding 1GB, per the rule:

2023-04-21 17:49:10.9612--INFO--Detected _Node_0 is in Warning.
Disk repair is enabled. 7 logic rules found for Disk repair.
2023-04-21 17:49:11.1356--INFO--Executing logic rule 'Mitigate(MetricName=?MetricName) :- LogRule(61), match(?MetricName, "DiskSpace"), GetRepairHistory(?repairCount, 08:00:00),  ?repairCount < 4, member(config(?X,?Y), [config("C:\cluster_observer_logs", 1), config("C:\fabric_healer_logs", 1), config("C:\fabric_observer_logs", 1)]), CheckFolderSize(?X, MaxFolderSizeGB=?Y), DeleteFiles(?X, SortOrder=Ascending, MaxFilesToDelete=10, RecurseSubdirectories=true).'
2023-04-21 17:49:11.1563--INFO--Directory C:\cluster_observer_logs size: 8300000000 bytes.
2023-04-21 17:51:04.0166--INFO--Executing repair predicate 'DeleteFiles(C:\cluster_observer_logs,SortOrder=Ascending,MaxFilesToDelete=10,RecurseSubdirectories=True)'
2023-04-21 17:51:04.1068--INFO--Successfully created repair task FH/24c1971b-b0b9-41e1-a2e2-ed1ae5715d85/DeleteFiles/_Node_0.
2023-04-21 17:51:04.1213--INFO--Waiting for RM to Approve repair task FH/24c1971b-b0b9-41e1-a2e2-ed1ae5715d85/DeleteFiles/_Node_0.
2023-04-21 17:51:09.1514--INFO--RM has Approved repair task FH/24c1971b-b0b9-41e1-a2e2-ed1ae5715d85/DeleteFiles/_Node_0.
2023-04-21 17:51:09.1596--INFO--Executing repair FH/24c1971b-b0b9-41e1-a2e2-ed1ae5715d85/DeleteFiles/_Node_0.
2023-04-21 17:51:09.1621--INFO--Attempting to delete files in folder C:\cluster_observer_logs on node _Node_0.
2023-04-21 17:51:10.0197--INFO--Successfully deleted up to 10 files in C:\cluster_observer_logs

**Comment by GitTorre** [comment]
What version of FO are you running, just out of curiosity? (It should not really matter, but just want to know).

**Comment by GitTorre** [comment]
Are you sure the paths are correct?

**Comment by GitTorre** [comment]
Is FH deployed to the node where FO detects the problem? If you are seeing no telemetry that FH detected a node in Warning, then that means FH is not running on said node. For Disk Repair, FH has to be running where FO detects Disk space or folder size issues and emits a related warning.

**Comment by markwragg** [comment]
FO version is 3.2.1 I believe.

I have FH set to run on every node.

**Comment by GitTorre** [comment]
I will need to test with that version of FO, but it shouldn't really matter in this case. Will get back to you. BTW, 3.2.7 will ship next week, probably Monday..I was testing this scenario with that FO version submitting the facts.

**Comment by GitTorre** [comment]
That's actually the problem... FO 3.2.1 has a _different_ version of EntityType than what FH versions 1.2.x expect.

So, FO 3.2.1 reports EntityType.Disk (enum value == 10), but that that is actually mapped to EntityType.Replica (enum value == 10) in the _current_ version**s** of FH. That is, 3.2.1 is an older version of FO and it is not fully supported by newer versions of FH. I should add this to the README. 

So, you see nothing happening because the data from FO that FH Deserializes back into a TelemetryData instance does not contain the same EntityType definition as FO. In FH modern versions, the EntityType enum values are off by one compared to the older FO versions.

This is all an evil plot to get folks to stay up to date on both FO and FH! :) 

There is no recourse here except to upgrade FO.

**Comment by markwragg** [comment]
Great, thanks for figuring that out. I'll do the upgrade early next week and retest.

**Comment by GitTorre** [comment]
Thanks. Of course, I should have added a new member to the *end* of the enum value list, not at the top. 

I really appreciate all the testing and bugs you have reported. I'll do a better job of not breaking things.

**Comment by markwragg** [comment]
Just  to update you, I updated to the latest release of Fabric Observer (and Cluster Observer) and can see this working now. I did have a bit of weirdness with Fabric Observer where initially it didn't seem to want to trigger the warning for disk space on C:\, even though diskobserver was enabled. I ran a stress test tool and got CPU and Memory warnings to trigger, so then I enabled telemetry and diskobserver, restarted the FabricObserver.exe process and then weirdly the disk space warning started to appear (and FabricHealer did its thing).

**Comment by GitTorre** [comment]
Thanks for the update. Glad to hear this. 

Re DiskObserver: it could be that at the time the disk space was measured, the result did not exceed the specified related threshold. ETW has no impact on whether or not an observer reports a Warning. By restarting the process, DiskObserver ran again. Do you have a run interval set for it?
