### ISSUE TITLE
[RepairData property is not loaded into custom predicate type from custom plugin]

### ISSUE THREAD

**Issue by imantsp** [microsoft/service-fabric-healer#182]
It is relevant for the case when the custom predicate is called within the rule from one of the following files:
DiskRules.guan, FabricNodeRules.guan, ReplicaRules.guan

The problem is within the call of RepairTaskManager.StartRepairWorkflowAsync which is called in some cases without passing serializedRepairData parameter

**Describe the bug**

**Steps To Reproduce**

**Expected behavior**

**OS:**
 - Name:
 - Version:

**Additional information:**

**Comment by sidhant012** [comment]
Hi @imantsp,

Thanks for catching this! We will be sure to fix this in our next release

**Comment by sidhant012** [comment]
Will be fixed in the 1.2.15 release
